# Generated by Django 4.2.4 on 2023-08-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Empleado',
        ),
    ]
